package com.bot.bot.engine;

/**
 *
 * @param filepath
 * @param linenumber
 * @param message
 * @param severity
 * @param suggestions
 * @param source
 * @param confidence
 * DTO for the findings generated by the heuristics and LLM.
 * This will be used to store the findings in the database and also to return the findings to the client.
 * The source field is used to indicate whether the finding was generated by a heuristic or by the LLM.
 * This can be useful for debugging and for understanding the strengths and weaknesses of each approach.
 * The confidence field is used to indicate how confident the system is about the finding.
 * This can be useful for prioritizing the findings and for understanding which findings are more likely to be true positives.
 */

public record Finding (
    String filepath,    // Path of the file where changes happened
    int linenumber,     // Line number where the change happened
    String message,
    Severity severity,
    String suggestions,
    String source,      //"heuristic" or "llm"
    double confidence   // 0.0 to 1.0
    ){
    public Finding withSource(String source){
        return new Finding(filepath, linenumber, message, severity, suggestions, source, confidence);
    }
}
