package com.bot.bot.engine;

import com.bot.bot.domain.Finding;
import com.bot.bot.github.GitHubApiClient;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Mono;

import java.util.*;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class ReviewPublisher {
    private final GitHubApiClient gitHubApiClient;

    public Mono<Void> publishReview(String owner, String repo, int prNumber, List<Finding> findings) {
        if (findings == null || findings.isEmpty()) {
            log.info("No issues found for {}/{}/PR#{}", owner, repo, prNumber);
            return gitHubApiClient.postComment(owner, repo, prNumber, "✅ No issues found!");
        }

        log.info("Publishing review for {}/{}/PR#{} with {} findings", owner, repo, prNumber, findings.size());
        String reviewBody = formatReview(findings);
        return gitHubApiClient.postComment(owner, repo, prNumber, reviewBody);
    }

    private String formatReview(List<Finding> findings) {
        StringBuilder sb = new StringBuilder();
        sb.append("## 🔍 Code Review Analysis\n\n");

        // Group by severity
        Map<String, List<Finding>> bySeverity = findings.stream()
                .filter(Objects::nonNull)
                .collect(Collectors.groupingBy(
                        f -> f.getSeverity() != null ? f.getSeverity() : "UNKNOWN",
                        LinkedHashMap::new,
                        Collectors.toList()
                ));

        for (String severity : List.of("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO")) {
            List<Finding> severityFindings = bySeverity.getOrDefault(severity, List.of());

            if (!severityFindings.isEmpty()) {
                String emoji = switch (severity) {
                    case "CRITICAL" -> "🔴";
                    case "HIGH" -> "🟠";
                    case "MEDIUM" -> "🟡";
                    case "LOW" -> "🔵";
                    default -> "ℹ️";
                };

                sb.append("### ").append(emoji).append(" ").append(severity)
                        .append(" (").append(severityFindings.size()).append(")\n\n");

                for (Finding finding : severityFindings) {
                    String filePath = finding.getFilePath() != null ? finding.getFilePath() : "(unknown)";
                    String category = finding.getCategory() != null ? finding.getCategory() : "GENERAL";
                    String message = finding.getMessage() != null ? finding.getMessage() : "";
                    String suggestion = finding.getSuggestion();
                    String source = finding.getSource() != null ? finding.getSource() : "UNKNOWN";

                    sb.append("- **").append(category).append("** in `").append(filePath).append(":")
                            .append(finding.getLineNumber()).append("`\n");
                    sb.append("  - ").append(message).append("\n");

                    if (suggestion != null && !suggestion.isEmpty()) {
                        sb.append("  - 💡 Suggestion: ").append(suggestion).append("\n");
                    }

                    sb.append("  - Source: ").append(source)
                            .append(" (Confidence: ")
                            .append(String.format("%.0f%%", Math.min(1.0, Math.max(0.0, finding.getConfidence())) * 100))
                            .append(")\n\n");
                }
            }
        }

        sb.append("---\n");
        sb.append("*Review generated by PR Review Bot*\n");

        return sb.toString();
    }
}
