package com.bot.bot.engine;

import com.bot.bot.domain.Finding;
import com.bot.bot.github.GitHubApiClient;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Mono;

import java.util.*;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class ReviewPublisher {
    private final GitHubApiClient gitHubApiClient;

    public Mono<Void> publishReview(String owner, String repo, int prNumber, List<Finding> findings) {
        log.info("Publishing review for {}/{}/PR#{} with {} findings", owner, repo, prNumber, findings.size());

        if (findings.isEmpty()) {
            return gitHubApiClient.postComment(owner, repo, prNumber, "✅ No issues found!");
        }

        String reviewBody = formatReview(findings);
        return gitHubApiClient.postComment(owner, repo, prNumber, reviewBody);
    }

    private String formatReview(List<Finding> findings) {
        StringBuilder sb = new StringBuilder();
        sb.append("## 🔍 Code Review Analysis\n\n");

        // Group by severity
        Map<String, List<Finding>> bySeverity = findings.stream()
                .collect(Collectors.groupingBy(Finding::getSeverity));

        for (String severity : List.of("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO")) {
            List<Finding> severityFindings = bySeverity.getOrDefault(severity, new ArrayList<>());

            if (!severityFindings.isEmpty()) {
                String emoji = switch (severity) {
                    case "CRITICAL" -> "🔴";
                    case "HIGH" -> "🟠";
                    case "MEDIUM" -> "🟡";
                    case "LOW" -> "🔵";
                    default -> "ℹ️";
                };

                sb.append("### ").append(emoji).append(" ").append(severity).append(" (").append(severityFindings.size()).append(")\n\n");

                for (Finding finding : severityFindings) {
                    sb.append("- **").append(finding.getCategory()).append("** in `").append(finding.getFilePath()).append(":")
                            .append(finding.getLineNumber()).append("`\n");
                    sb.append("  - ").append(finding.getMessage()).append("\n");

                    if (finding.getSuggestion() != null && !finding.getSuggestion().isEmpty()) {
                        sb.append("  - 💡 Suggestion: ").append(finding.getSuggestion()).append("\n");
                    }

                    sb.append("  - Source: ").append(finding.getSource())
                            .append(" (Confidence: ").append(String.format("%.0f%%", finding.getConfidence() * 100)).append(")\n\n");
                }
            }
        }

        sb.append("---\n");
        sb.append("*Review generated by PR Review Bot*\n");

        return sb.toString();
    }
}